Add example datagen, misc changes
neoforged/MDK pull request #10
Opened 2023-08-19 06:04 UTC by TeamDman

Some defaults that I personally use when starting a new mod, figured I'd share.

Included:
- Separate datagen and gametest sourcesets from main to reduce build jar size
- Add example datagen
    - Textures, models, localizations, recipes, loot table
- Add example block item to example creative tab
- Add package-info.java with stricter behaviour checking
- Add JBR hot reload VM options
- Add note in README.md regarding forcing IDEA to detect changes to runconfigs after genIntellijRuns

2023-08-19 19:08 UTC, PaintNinja requested changes

2023-08-19 19:08 UTC, PaintNinja commented on build.gradle
> +    for (def configuration : configurations) {
```suggestion
    for (configuration in configurations) {
```

2023-08-19 19:08 UTC, PaintNinja commented on build.gradle
> +processResources {
Use the existing processResources withType configuration further down

2023-12-01 14:04 UTC, Technici4n requested changes
This is too much for a basic template that everyone will use. Most of the stuff here should be in the documentation, not in the MDK.

2023-12-01 17:23 UTC, closed without merging