Update setup process
neoforged/MDK pull request #17
Opened 2023-11-17 00:52 UTC by tmvkrpxl0

`genIntellijRuns` and `genEclipseRuns` no longer exist and this section should be removed.

2023-11-17 06:59 UTC, sciwhiz12 requested changes

2023-11-17 06:59 UTC, sciwhiz12 commented on README.md
> +Once you have your clone, you can initialize your copy. Then simply open the template in IDE of your choice, we recomment Eclipse and Intellij.
First, the phrase "initialize your copy" is now obsolete, since that refers to the IDE run generation tasks which NG7 has removed. Second, typo: `recommet` -> `recommend`. I've also adjusted it outside of those two, with some rewording and small additions.

```suggestion
Once you have your clone, simply open the repository in the IDE of your choice. The usual recommendation for an IDE is either IntelliJ IDEA or Eclipse.
```

2023-11-19 11:30 UTC, sciwhiz12 approved these changes

2023-11-21 14:22 UTC, Commoble commented
We should mention that you have to run gradlew runClient from CLI before the eclipse run config works

2023-11-23 17:04 UTC, sciwhiz12 requested changes

2023-11-23 17:04 UTC, sciwhiz12 commented on README.md
> +**Note**: On Eclpse you need to run `runClient` first from CLI to make run configs work.
A typo fix, some formatting (put note into a quote for emphasis), and a bit of clarification on what should be done.
```suggestion
Once you have your clone, simply open the repository in the IDE of your choice. The usual recommendation for an IDE is either IntelliJ IDEA or Eclipse.

> **Note**: For Eclipse users, you must run the `runClient` task first from the terminal (such as `./gradlew runClient`) for the run configs to work.
```

@Commoble: what do you mean by "before the eclipse run config works"? 

Does that mean any change to the run config definition require rerunning the task manually from the terminal again (as opposed to manually running the task only once after cloning the repository, and never again manually)? 

Does the `runClient` task (re)generate the run config, or cause certain things needed by the run config to be created?

2023-11-23 18:04 UTC, Commoble commented on README.md
> +**Note**: On Eclpse you need to run `runClient` first from CLI to make run configs work.
I dunno, the eclipse run configs didn't work for me until I ran runClient from cmd first

2023-11-24 14:02 UTC, sciwhiz12 commented on README.md
> +**Note**: On Eclpse you need to run `runClient` first from CLI to make run configs work.
@marchermans, have you received any reports about this from Eclipse users?

@Shadows-of-Fire, I believe you use Eclipse -- perhaps you have experience with this?

2023-11-24 15:20 UTC, Nightenom commented on README.md
> +**Note**: On Eclpse you need to run `runClient` first from CLI to make run configs work.
After quick investigation: this happens for vscode too, but gets fixed if you run `ideBeforeRunTask`

2023-12-01 13:58 UTC, GeorgBurkl approved these changes

2023-12-01 13:58 UTC, Minecraftschurli approved these changes

2023-12-01 14:42 UTC, merged