Big Update
neoforged/MDK pull request #42
Opened 2024-02-25 18:18 UTC by Spinoscythe

Update to Neo stable and foojay, enable support for DCEVM and automatically add access transformers when present
Also supersedes #38

2024-02-25 18:22 UTC, pupnewfster commented
Based on https://github.com/neoforged/MDK/issues/24#issuecomment-1868233705 I am not sure if the logging properties should be changed (though fixing the gametest ones definitely is good)

2024-02-25 18:24 UTC, pupnewfster commented on build.gradle
> +        }
Also this isn't enough to just support DCEVM out of the box if that was your intention. It just makes it so if you are using it then it gets properly enabled. To make it enabled by default you would need to set it via the toolchain, and also update the gradle wrapper to at least 8.4 so that it can provide the jetbrains one

2024-02-25 18:25 UTC, Spinoscythe commented
got it

2024-02-25 18:32 UTC, Spinoscythe commented on build.gradle
> +        }
My intention indeed WAS to make it so that if you are using it then it gets properly enabled

2024-02-25 21:56 UTC, FiniteReality commented on build.gradle
> +        }
I don't think this is necessary; I would instead suggest something like this:
```
// If you wish to use enhanced class hotwsapping during debug (DCEVM), uncomment this line.
// java.toolchain.vendor = JvmVendorSpec.JETBRAINS // NOTE: Requires Gradle 8.4 or above
```
```
// If you wish to use enhanced class hotwsapping during debug (DCEVM), uncomment this block.
/*
runs.configureEach {
    it.jvmArgument "-XX:+AllowEnhancedClassRedefinition"
}
*/
```

2024-02-26 13:02 UTC, marchermans approved these changes

2024-02-28 05:26 UTC, XFactHD requested changes

2024-02-28 05:26 UTC, XFactHD commented on build.gradle
> +if (rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')) {
This check is missing an `exists()` call, without it this always evaluates to true and then fails later, which is also why the build check of this PR is currently failing

2024-02-28 05:26 UTC, XFactHD commented on build.gradle
> +        if (run.project.javaToolchains.launcherFor(java.toolchain).map { it.metadata.vendor }.getOrElse("").contains("JetBrains")) {
I'm not really a fan of adding something so specific to the MDK. Using DCEVM is an advanced configuration and comes with its own set of problems. Without any documentation this also looks like a completely arbitrary check to anyone not already familiar with DCEVM. I personally would prefer having the docs mention the possibility of using DCEVM and what is required to set it up instead of having this in the MDK, especially considering that this is nowhere near the complete setup.

2024-02-28 16:56 UTC, Spinoscythe commented on build.gradle
> +if (rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')) {
fixed!

2024-02-28 17:21 UTC, XFactHD commented on build.gradle
> +        if (run.project.javaToolchains.launcherFor(java.toolchain).map { it.metadata.vendor }.getOrElse("").contains("JetBrains")) {
Commenting the entire block out as-is is not what I meant. If it's commented out and has a comment explaining what it's for, then the check is unnecessary. It should either be what FiniteReality mentioned above with two simple, commented-out blocks or (preferably, in my opinion) removed entirely from the MDK and instead documented on our docs

2024-03-13 21:23 UTC, Spinoscythe commented
I want to redo this

2024-03-13 21:23 UTC, closed without merging