Big Update
neoforged/MDK pull request #44
Opened 2024-03-13 21:49 UTC by Spinoscythe

1. update to gradle 8.6, making this a sister PR to [neoforged/NeoForge#708](https://github.com/neoforged/NeoForge/pull/708)
2. enable support for DCEVM
3. update parchment
4. auto-add ATs

2024-03-14 01:34 UTC, ChampionAsh5357 requested changes

2024-03-14 01:34 UTC, ChampionAsh5357 commented on build.gradle
> +// java.toolchain.vendor = JvmVendorSpec.JETBRAINS // NOTE: Requires Gradle 8.4 or above
Duplicate of above?

2024-03-14 01:34 UTC, ChampionAsh5357 commented on build.gradle
> +// java.toolchain.vendor = JvmVendorSpec.JETBRAINS
Assume people don't know why DCEVM is. Link something and why you must specifically use the Jetbrains runtime instead of any other.

2024-03-14 01:34 UTC, ChampionAsh5357 commented on build.gradle
>  //minecraft.accessTransformers.entry public net.minecraft.client.Minecraft textureManager # textureManager
Why are we leaving this line here if the rest of the AT is moved somewhere else?

2024-03-14 01:34 UTC, ChampionAsh5357 commented on build.gradle
> +}
This is not as true anymore as the access transformer is specified by the `mods.toml` information, so this should be also setting the replacement variable there.

2024-03-14 01:34 UTC, ChampionAsh5357 commented on build.gradle
> +    configureEach { net.neoforged.gradle.dsl.common.runs.run.Run run ->
Why is this being changed here? and why are you only doing it for the `configureEach` block?

2024-03-14 01:34 UTC, ChampionAsh5357 commented on build.gradle
> +        // }
What's the point in having this part commented out if the vendor settings is also commented out, which would normally set this property? Also, this should be linked to the mention of DCEVM above rather than treating the two as separate things based on the wording.

2024-03-14 01:34 UTC, ChampionAsh5357 commented on build.gradle
> +        // If you're interested, download the apt version of JBR at https://github.com/JetBrains/JetBrainsRuntime/releases, and set it as your Project SDK via Project Structure -> SDK.
What is the `apt` version?

2024-03-14 01:35 UTC, ChampionAsh5357 commented
Also, update all the `forge` prefixes to `neoforge` please.

2024-03-14 02:14 UTC, Shadows-of-Fire commented on build.gradle
> +}
Yeah, the AT file path needs to be a gradle.properties variable and replace the file checked here *and* the line in the mods.toml

A sophisticated solution can make editing the mods.toml unnecessary for adding the AT through replacements, but we may not want to do it here for example purposes (since the automatic modification of mods.toml obscures some things).

2024-03-14 04:38 UTC, XFactHD requested changes

2024-03-14 04:38 UTC, XFactHD commented on build.gradle
> +// java.toolchain.vendor = JvmVendorSpec.JETBRAINS
Quoting from the previous PR because I still stand by that:
> I'm not really a fan of adding something so specific to the MDK. Using DCEVM is an advanced configuration and comes with its own set of problems. Without any documentation this also looks like a completely arbitrary check to anyone not already familiar with DCEVM. I personally would prefer having the docs mention the possibility of using DCEVM and what is required to set it up instead of having this in the MDK, especially considering that this is nowhere near the complete setup.

2024-03-14 19:08 UTC, Spinoscythe commented on build.gradle
> +    configureEach { net.neoforged.gradle.dsl.common.runs.run.Run run ->
yeah I just took inspiration from mekanism, guess I'll change that

2024-03-17 11:31 UTC, Spinoscythe commented
> Also, update all the `forge` prefixes to `neoforge` please.

@ChampionAsh5357 I did this previously, but @pupnewfster recommended to only update the gametest run

2024-03-29 15:50 UTC, Spinoscythe commented
@Mrbysco in `mods.toml` now

2024-03-30 21:56 UTC, sciwhiz12 requested changes
In the future, please don't bunch up many unrelated changes into a single PR, since it means all changes in the PR have to be reviewed all at once rather than each change being reviewed in its own right. This also means your PR title should be descriptive of your changes: "Big Update" doesn't mean anything (and it's hard to be more descriptive when there's many different changes in one).

Also, in the future, if you made a previous PR which you're recreating (as does this for #42), at the minimum link to that previous PR so the context of previous reviews can be taken into account. 

Additionally, don't make a new PR if your previous and current PR are substantially the same. Revert existing commits, make new commits reverting your changes manully, or recreate your commits and force-push your local branch to the PR branch; all these preserve the history of your PR, which is useful for reviewers past and present.

2024-03-30 21:56 UTC, sciwhiz12 commented on build.gradle
> +        // Comment this if you're not using the JetBrainsRuntime.
Why is this not commented out by default, but the line to change the JVM vendor to JetBrains (which contains DCEVM) is commented out by default?

2024-03-30 21:56 UTC, sciwhiz12 commented on build.gradle
> +        // For more information, read the documentation at https://forge.gemwire.uk/wiki/Hotswap
I'm not so sure with linking from our MDK to the Forge Community Wiki/FCW, and not to a page on our own official documentation site https://docs.neoforged.net/.

2024-04-02 15:16 UTC, Shadows-of-Fire commented
The AT's still need to be present in the build.gradle file so that they get applied to the project's decompiled source, the entry in the mods.toml file is only used at runtime.

2024-04-15 18:06 UTC, closed without merging