Respect the archivesName
neoforged/MDK pull request #46
Opened 2024-03-30 06:40 UTC by uecasm

I'm not a gradle expert, so I'm not sure if there's a better way to do this, but at least with userdev 7.0.97 (as is referenced here), changes to the `base.archivesName` don't actually do anything without a line like this.

2024-03-30 20:03 UTC, Shadows-of-Fire commented
Default maven path before this change:
`com\example\examplemod\MDK-main\1.0.0\MDK-main-1.0.0.jar`
Default maven path after this change:
`com\example\examplemod\examplemod\1.0.0\examplemod-1.0.0.jar`

2024-03-30 20:03 UTC, Shadows-of-Fire approved these changes

2024-03-30 21:45 UTC, sciwhiz12 requested changes
Per the [Gradle User Guide](https://docs.gradle.org/8.6/userguide/publishing_maven.html#sec:identity_values_in_the_generated_pom), the default value of `artifactId` is based off `Project#getName()` rather than the base archive name.

Should we consider setting the project name to the mod ID in addition to (or perhaps in replacement of) this change?

2024-03-30 21:45 UTC, sciwhiz12 commented on build.gradle
> +            artifactId = project.base.archivesName.get()
I think this should be in an `afterEvaluate` block, to avoid any potential problems with the value of the `archivesName` property being set at a different time (whether in a block after `publishing` in the buildscript, or the property itself being fed its value by a provider).

2024-03-30 21:51 UTC, Shadows-of-Fire commented
I wasn't sure if there would be other implications of fiddling with the project name (does it change the name displayed in an IDE?)

Also, the project name is seldom the modid, rather it is usually the mod name without spaces (due to repository naming schemes).

2024-03-30 22:04 UTC, sciwhiz12 commented
> (does it change the name displayed in an IDE?)

It does; if I recall correctly, IDEA displays the folder name and then in parentheses the project name (or was it the other way around?).

> Also, the project name is seldom the modid, rather it is usually the mod name without spaces (due to repository naming schemes).

Good point. I think, though, the more pertinent issue (as I've just remembered) is a problem with case-insensitive file-systems, where a case difference between the mod ID and the repository/folder name might cause issues. (I think I remember having experienced this issue on Windows when I used Eclipse, and possibly with IDEA.)

2024-03-31 01:06 UTC, uecasm commented
The motivating case was when I was trying to set the archivesName like so:

```
base {
    archivesName = "MyModName-${minecraft_version}"
}
```

This is, I think, fairly typical, where the project id/name is the mod id (or folder name?) but the archive name is set to a capitalized/de-spaced friendly mod name, with Minecraft version included (so that it's not part of the actual mod version).

2024-03-31 09:04 UTC, sciwhiz12 commented
I think I can agree with those changes: creating/publishing the sources JAR by default (via `java.withSourcesJar()`), and adding the Minecraft version to the base archives name.

2024-04-01 02:01 UTC, uecasm commented
How's this look?  I changed the archive name to use the project name by default (rather than the mod id, which may or may not be the same), mostly because the `mod_name` can't be assumed to be space-free.  But mod authors can still edit it as needed to get the desired artifact name.

2024-04-01 03:36 UTC, Technici4n commented on build.gradle
> +    archivesName = "${name}-${minecraft_version}"
Using the project name is not great because it is derived from the folder name if it is not given in settings.gradle. I would keep the modid.

2024-04-01 03:38 UTC, Shadows-of-Fire commented on build.gradle
> +    archivesName = "${name}-${minecraft_version}"
We should introduce a `file_name` property to `gradle.properties` and use that instead - it makes it explicit and clarifies the intent.

2024-04-02 07:45 UTC, Technici4n approved these changes

2024-04-02 15:11 UTC, Shadows-of-Fire commented on build.gradle
> +            artifactId = project.base.archivesName.get()
This is *probably* a non-issue as far as the MDK is concerned.

Anyone messing with the declaration such that the `afterEvaluate` would be necessary should know how to fix it.

2024-04-02 15:12 UTC, Shadows-of-Fire approved these changes

2024-04-02 21:15 UTC, sciwhiz12 commented on build.gradle
> +            artifactId = project.base.archivesName.get()
Do we lose out on anything if we introduce the `afterEvaluate` here, though? If it can only improve the buildscript, then I say it's worth doing now instead of foisting the burden to others in the future.

2024-04-02 21:19 UTC, Shadows-of-Fire commented on build.gradle
> +            artifactId = project.base.archivesName.get()
Use of `afterEvaluate` is too complicated for the target audience of the MDK and could introduce confusion - even explaining it in reasonable detail requires a fair understanding of gradle that many do not possess.

2024-04-06 03:51 UTC, sciwhiz12 commented on build.gradle
> +            artifactId = project.base.archivesName.get()
Hmmm. I'll let this slide for now, but I do hope this doesn't cause more issues down the line for mod developers.

2024-04-06 03:53 UTC, sciwhiz12 requested changes

2024-04-06 03:53 UTC, sciwhiz12 commented on build.gradle
> +}
Move this above the comment (which is for the `publishling` block), and add its own comment explaining that this enables the creation of the `-sources` JAR.

2024-04-06 03:53 UTC, sciwhiz12 commented on build.gradle
> +            mod_id              : mod_id, mod_name: mod_name, file_name: file_name, mod_license: mod_license, mod_version: mod_version,
I don't think we need to supply the file name as a property to the `mods.toml` properties expansion. Note that `mod_group_id` is also not provided as a property here.

2024-04-07 19:40 UTC, lukebemish requested changes

2024-04-07 19:40 UTC, lukebemish commented on build.gradle
> +            artifactId = project.base.archivesName.get()
The actual `register` block is already lazy so it should be fine

2024-04-07 19:40 UTC, lukebemish commented on build.gradle
> +    archivesName = "${file_name}-${minecraft_version}"
This PR has set the base archives name to be the name of the published module -- however, you're now publishing the artifact at `com.example.examplemod:ExampleMod-1.20.4`. By convention, module names are lowercase, so this is not great. The inclusion of the minecraft version in the module name is also not optimal - it means that someone could depend on both `ExampleMod-1.20.4` and, say, `ExampleMod-1.20.2` and gradle would just pull in both -- whereas publishing every version of a mod under the same module name wouldn't allow this to happen.

The other solution to the latter problem is the use of capabilities but that is *way* to complicated for the MDK.

2024-04-07 19:40 UTC, lukebemish commented on gradle.properties
> +file_name=ExampleMod
See above: the file name can be this for the local file and that's fine, but for the published module (the bit in the publishing block) it should be a normal, conventional module name -- in this case, probably `com.example.examplemod:examplemod`. A simple way to do this is to set the `rootProject.name` in the settings.gradle.

2024-04-09 07:51 UTC, uecasm commented on build.gradle
> +    archivesName = "${file_name}-${minecraft_version}"
Almost every mod file I've ever seen has published using WordCase names.

2025-06-12 13:21 UTC, Matyrobbrt commented
This repository now only serves as an archive of the old branches and as a target for legacy branches. Please retarget this PR to the [mod generator](https://github.com/neoforged/mod-generator)

2025-06-12 13:21 UTC, closed without merging